### PR TITLE
Implement reinstall

### PR DESCRIPTION
**Pull request by kolsa**

### CODE REVIEW

**Comment by majst01** [comment]
to much differences, should only add the new structs and methods, what version of swagger did you use ?

**Comment by kolsa** [comment]
swagger v0.19.0

**Comment by majst01** [comment]
got it, its because of @Gerrit91 sorted metal-api.json mechanism, no logical changes so far.

**Comment by majst01** [comment]
Need to be updated to the new organistation (metal-pod -> metal-stack)

**Pull request closed without merging**
