### PR TITLE
Allow public client usage

### PR DESCRIPTION
**Pull request by Gerrit91**
This PR allows direct access to the generated client, allowing APIs to migrate to generated client structs without using wrappers.

For better testing, the generated client is flattened into a single interface, such that no "sub clients" are required anymore.

```ACTIONS_REQUIRED
Please migrate your clients to use the `Client` interface that is now returned by the `NewDriver` function. The old driver implementation can still be used, but will be removed at some point in the future. 
```

### CODE REVIEW

**Comment by majst01** [comment]
With this, all funcs of different entities must not overlap if i understand it correct, this is wrong !

**Comment by Gerrit91** [comment]
Kind of. We would come into trouble already if we'd introduced a v2 and use identical operation ids (would cause collisions inside the same package). For the next version we need to prefix the operation names properly, to circumvent this problem, maybe just use the automatically proposed id?

```
operationId is an optional unique string used to identify an operation. If provided, these IDs must be unique among all operations described in your API.
``` 

From: https://swagger.io/docs/specification/paths-and-operations/

So, using same ids across different packages is prohibited anyway.

**Comment by majst01** [comment]
But the current approach prevents this by design and makes the API obvious, removing the package by entity is from may POV not acceptable.

**Comment by Gerrit91** [comment]
It is not prevented at the moment. If you name operations the same with the current impl then the generator will only produce code in one package.

**Comment by Gerrit91** [comment]
I tried to make the changes less intrusive and closer to the way we deal with our gRPC clients.

**Pull request merged**
